[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
name = "sklearn-ecosystem"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
convert-to-notebooks = { cmd = "jupytext --to notebook ./python_files/*.py && mkdir -p ./notebooks && mv ./python_files/*.ipynb ./notebooks" }

[dependencies]
python = ">=3.13.2,<3.14"
sqlite = "<3.49"

[pypi-dependencies]
ipython = "*"
ipykernel = "*"
jupyterlab = "*"
jupytext = "*"
rich = ">=13.9.4, <14"
ruff = ">=0.9.9, <0.10"
scikit-learn = ">=1.6.1, <2"
sentence-transformers = ">=3.4.1, <4"
plotly = ">=6.0.0, <7"
ipywidgets = ">=8.1.5, <9"
skops = { path = "/Users/glemaitre/Documents/scratch/skops", editable = true }
skore = ">=0.8.1, <0.9"
skrub = ">=0.5.1, <0.6"

